### ISSUE TITLE
"Set user page as Home Page" option breaks redirect

### ISSUE THREAD

**Issue by DunklerPhoenix** [JulianPrieber/littlelink-custom#369] opened 2023-03-21 14:57 UTC
Platform: `Debian Buster`
Server type: `Docker.`
PHP version: `8.1`

As I mentioned in this comment https://github.com/JulianPrieber/llc-docker/issues/38#issuecomment-1477976167 the option "Set user page as Home Page" breaks the redirects for me. 
If I set it back to "default" and use "disable_home_page" from the advanced editor instead everything works fine.

Did I misunderstood this option or is it a bit buggy?

**Comment by JulianPrieber** [comment] 2023-03-21 15:02
I might be reading the context wrong here, but from what I'm understanding, the option is working exactly as intended.

Could you describe your issue in a bit more detail?

**Comment by DunklerPhoenix** [comment] 2023-03-21 18:13
I understood the option like this:
- If its set to default, then the standard homepage is shown and you can still access the sites of the users /@.userA* 
- If its set to userA, then the standard homepage is accessible via /home and the page of userA gets displayed at /@. userB* is still aaccessible via /@.userB*

How it works at the moment for me:
- If its set to default, then the standard homepage is shown and you can still access the sites of the users /@.userA* 
- If its set to userA, then the page of userA gets displayed at /@. Now any other user site is not accessible anymore. e.g. /@.userB* redirects to /. Didn't test /home

* "." because of githubs linking function

**Comment by JulianPrieber** [comment] 2023-03-21 18:52
Yeah, you're right, I see your problem now.
I'm not even sure if we can consider this a bug, we didn't really account for anyone doing this during development.

**Comment by DunklerPhoenix** [comment] 2023-03-21 18:56
Hmm.. For what purpose is this option originally planned?
Is it to disable Multiuser? So that only one user can be active in an instance?

At the moment it looks like a duplicate of the disable_home_page feature (from description).
The disable_home_page is for my case exactly what I need and use now. Maybe it's just enough to clarify this option description a little bit.

**Comment by DunklerPhoenix** [comment] 2023-03-21 19:03
`The option to set a user as the home page is exactly only designed for single user applications. Most people only have one user on the site, so this is an option most people use for their instances.`

Ah okay. This is not really clear from the discription. Maybe just add something like "This disables the usage of other profiles".

**Comment by JulianPrieber** [comment] 2023-03-21 19:07
> Maybe just add something like "This disables the usage of other profiles".
> Originally i thought that this option does replace the homepage with a userpage, but let the other pages still active.

Well, during development, we only considered this single user mode. We didn't really think about anyone using single user mode with multiple users.

Not sure why you would want that, but I see no reason why this shouldn't be possible.

I'll look into restoring the use of multiple users with this kind of setup. I just looked into the source code, and I'm not sure how I would do something like this, but I'll try 👍

**Comment by DunklerPhoenix** [comment] 2023-03-21 19:14
`Not sure why you would want that`

I use LittleLink for our sports club. The original home page can only be edited by admins and (i think) only by code.
So I thought I create a new limited user, set his page as home and give this login out to someone who manage this "landing page"
All other users are not affected by that.

For the moment I'm be torn between:
- disable_home_page redirect = our_main_homepage.com
- disable_home_page redirect = /@.userA (didn't try that, maybe this is not even possible, but exactly what I think the other option is doing)

**Comment by JulianPrieber** [comment] 2023-03-21 19:28
Fixed in the latest beta

**Closed by JulianPrieber** 2023-03-21 19:28 UTC
