### ISSUE TITLE
Missing Graphic

### ISSUE THREAD

**Issue by lastsamurai26** [JulianPrieber/littlelink-custom#51] opened 2022-05-06 22:41 UTC
I don't know if this is really a bug.
I using the newest version 2.6.1

I find the following error messages in my logs. It seems that some graphics are missing but are being called?

"GET /studio/button-editor/images/grid2.png HTTP/2.0" 404
"GET /studio/button-editor/images/close.png HTTP/2.0" 404

Were there graphics forgotten to be delivered? 

after the update to the new versions the env editor does not load anymore =(

![Bildschirmfoto 2022-05-07 um 00 47 06](https://user-images.githubusercontent.com/3257844/167225232-9bca02b8-bed0-4a29-855d-c229420d234e.png)

**Comment by JulianPrieber** [comment] 2022-05-07 09:42
> I find the following error messages in my logs. It seems that some graphics are missing but are being called?

Thanks for pointing that one out, one of the images was missing and the other was added with the wrong path.


> after the update to the new versions the env editor does not load anymore =(

Dam, I didn't even notice that one. I saw mine not displaying once but wrote it up as my config not working, but I can confirm that this isn't working properly.

I'm not even sure why that is, I didn't even touch the config editor since the addition of the security check tool, and then it worked just fine.


I should probably do an open beta test for future revisions to prevent something like this. 
I will look into this and hopefully find a solution soon.

**Comment by lastsamurai26** [comment] 2022-05-07 10:12
If you need someone to help you with the beta analysis, just let me know so far I have waited for the final but since I always make a backup of all data I can also use the beta here, this is no problem for me :)


The Env Editor works in 2.5.9 without problems, the security check was already included there. I also thought something was wrong with my env config but after using the originals it still doesn't work.

**Comment by JulianPrieber** [comment] 2022-05-07 13:55
I'm pretty sure this commit is the reason for the Config Editor not working: https://github.com/JulianPrieber/littlelink-custom/commit/4eec538834c1828e2d6d7b3ed8f556ce34d9df45.

Now I just need to find a way to work around this, as the lines added in this commit are important for the Button Editor to work.

<br><br>


> If you need someone to help you with the beta analysis, just let me know so far I have waited for the final but since I always make a backup of all data I can also use the beta here, this is no problem for me :)

I would be more than happy to make a private channel on our Discord for beta testing new releases. If you're interested, feel free to join the Discord [here](https://discord.littlelink-custom.com).

**Comment by lastsamurai26** [comment] 2022-05-07 14:46
Ok, I will have another look at it later. 

I'm already on the LittleLink Custom Discord as Pyrosamu

**Comment by JulianPrieber** [comment] 2022-05-07 14:55
**The new release [v2.6.2](https://github.com/JulianPrieber/littlelink-custom/releases/tag/v2.6.2) is out now fixing the mentioned issues.**

<br>

> I find the following error messages in my logs. It seems that some graphics are missing but are being called?

> "GET /studio/button-editor/images/grid2.png HTTP/2.0" 404
> "GET /studio/button-editor/images/close.png HTTP/2.0" 404

Fixed with https://github.com/JulianPrieber/littlelink-custom/commit/9d3d0dcf973d32c2884bae92f3f516a139452997

<br>

> after the update to the new versions the env editor does not load anymore =(

Fixed with https://github.com/JulianPrieber/littlelink-custom/commit/cdfa580d366cfecbfb9d0cf9115bbe663587bc18


_Closing the issue._

**Closed by JulianPrieber** 2022-05-07 14:55 UTC
